### ISSUE TITLE
ExpiresBefore validation does not work

### ISSUE THREAD

**Issue by RaymondBakker** [ConnerPhillis/FluentLicensing#2]
It seems `ExpiresBefore` validation does not work as expected. `IfExpiresBefore` does work.

With a license that has an expiration date `DateTime.Today.AddDays(2);`

```cs
//Sample from README..
var validationResults = LicenseKeyManager.Load<LicenseSchema>(signedLicense)
    .ActivatesBefore(DateTime.UtcNow)
    .ExpiresBefore(DateTime.Today.AddDays(7), "License about to expire via ExpiresBefore()")
    .IfExpiresBefore(DateTime.UtcNow.AddDays(7), expirationDate
        => Console.WriteLine("License about to expire via IfExpiresBefore()"))
    .ExpiresAfter(DateTime.UtcNow, "License is expired")
    .Validate();

if (validationResults.HasErrors)
    foreach (var error in validationResults.Errors)
        Console.WriteLine(error);

//Own check..
LicenseKey<LicenseSchema> license;

LicenseKeyManager.Load<LicenseSchema>(signedLicense).GetLicenseKey(out license);

DateTime test = DateTime.Today.AddDays(7);
DateTime keyExpiry = license.ExpirationDate;

if (license.ExpirationDate <= test.ToUniversalTime())
{
    Console.WriteLine("License about to expire via own test");
}
```

Output:

```
License about to expire via IfExpiresBefore()
License about to expire via own test
Press any key to continue . . .
```

Expected output:

```
License about to expire via IfExpiresBefore()
License about to expire via ExpiresBefore()
License about to expire via own test
Press any key to continue . . .
```

**Comment by RaymondBakker** [comment]
Looks like this is caused by the return statements in `StandardLicenseValidator.cs`. How did this get through testing?

https://github.com/ConnerPhillis/FluentLicensing/blob/27b001e34c25fc3300f991d058e8628dc94b27e4/src/FluentLicensing/FluentLicensing/KeyValidation/StandardLicenseValidator.cs#L70

And more like these:

https://github.com/ConnerPhillis/FluentLicensing/blob/27b001e34c25fc3300f991d058e8628dc94b27e4/src/FluentLicensing/FluentLicensing/KeyValidation/StandardLicenseValidator.cs#L48

https://github.com/ConnerPhillis/FluentLicensing/blob/27b001e34c25fc3300f991d058e8628dc94b27e4/src/FluentLicensing/FluentLicensing/KeyValidation/StandardLicenseValidator.cs#L27

https://github.com/ConnerPhillis/FluentLicensing/blob/27b001e34c25fc3300f991d058e8628dc94b27e4/src/FluentLicensing/FluentLicensing/KeyValidation/StandardLicenseValidator.cs#L92

https://github.com/ConnerPhillis/FluentLicensing/blob/27b001e34c25fc3300f991d058e8628dc94b27e4/src/FluentLicensing/FluentLicensing/KeyValidation/StandardLicenseValidator.cs#L114

https://github.com/ConnerPhillis/FluentLicensing/blob/27b001e34c25fc3300f991d058e8628dc94b27e4/src/FluentLicensing/FluentLicensing/KeyValidation/StandardLicenseValidator.cs#L137

...

**Comment by RaymondBakker** [comment]
I've looked through the tests and it looks like all the non-if functions are written in a manner of `void(expected value, message if unexpected value)`, which would explain why the code sample above didn't work as I expected. 

This would make sense for use cases such as `ActivatesBefore(DateTime.Now)` and `ExpiresAfter(DateTime.Now)`. But for `ExpiresBefore` this seems very confusing. Can you clarify?

**Comment by ConnerPhillis** [comment]
Hi @RaymondBakker,

Wow, it's been a long time since I've looked over this code! I'm amazed people are using it, this was mostly a school project that I was hoping to use internally at my current organization.

So - to answer your question. Yes - all of the non If functions are written in the way that you've said. For example the documentation on `ExpiresBefore` states "check to see if the license expires before the given date / time". 

I admit that that could be a little more verbose, perhaps something like "check to see if the license expires before the given date / time, if it does not expire by the given date / time the validation fails and the message is added to errors" But I was younger then and less experienced with documentation and API design 😄 

Essentially this is how it works:
- non If - "does the license expire before this date? " -> yes -> no error
- if variant - "does the license expire before this date?" -> yes -> no error, invoke delegate

I assume what you were wanting to do was check to see if a license has expired, the code for that is written on the readme, and gives a pretty good idea of how the "if" and "non-if" functions are supposed to work. I've added an annotation and posted it below.

```cs
var signedLicense = GetSignedLicense();

if(!signedLicense.SignatureValid())
    throw new Exception("This license has been tampered with!");

var validationResults = LicenseKeyManager.Load<TestLicense>(signedLicense)
    .TypeNot(LicenseType.Trial)
    .ActivatesBefore(DateTime.UtcNow)
    .ExpiresAfter(DateTime.UtcNow, "License is expired")
    .MeetsCondition(license => license.LicenseData.IssuedTo == "Some Random User",
        "This license was issued to Some Random User, and you're not them!")
   /*
   this could have been written as:
   `.ExpiresAfter(DateTime.UtcNow.AddDays(7), "warning, license expires soon");`
   but that wouldn't make sense since that's a warning, not an error
   */
    .IfExpiresBefore(DateTime.UtcNow.AddDays(7), expirationDate 
        => Console.WriteLine("warning, license expires soon")
    .Validate();

if(validationResults.HasErrors)
    foreach(var error in validationResults.Errors)
        Console.WriteLine(error);
```

P.S.

You seem pretty new to github, so a quick bit of advice:

> Looks like this is caused by the return statements in StandardLicenseValidator.cs. How did this get through testing?

Statements like this can come off as really abrasive. You're essentially saying "your code is broke, you did a bad job testing this" which makes it seem like you're calling me an idiot and giving me a big fuck you. Maybe that was your intention, maybe it wasn't, and I certainty don't want to assume malice, but tbh it's hard to read any other way. Also, it pissed me off and made me not want to help you.

Let me just say first, I appreciate your thoroughness in looking through my code and trying to figure this out. Second, I am not an open source maintainer, I have a job that keeps me incredibly busy, and I really don't have the time for side projects like this. 

If you're going to file an issue on an open-source maintainer's project, someone who's thanklessly providing code that is likely to save you a lot of time essentially for free, you should probably be a little bit more respectful before you go out of your way to call them incompetent.

Have a good day!

**Comment by RaymondBakker** [comment]
Hi @ConnerPhillis,

Thanks for the clarification. If you have the time, may I suggest adding the information on if/nonif function variants you provided above to the readme, especially the two bullet points? I think this can help people who stumble upon this library in the future.

Regarding your P.S.:

I like providing extensive information when opening issues because I often see people reporting bugs and issues that are incomplete or without proper steps to reproduce issues (See the edit history of OP). I try to add what I'm doing and thinking while I am debugging so that the issue can function as a chronological notepad for myself and those who maintain it, which is how the test question came to be.

I saw tests were included in the repository so I wondered how the tests passed when I didn't get the expected result with using just the NuGet package. I can understand how one could assume this question to be malicious, but assuming and jumping to the wording and phrasing used above is a bit overkill and ridiculous, don't you agree?

Just to set the record straight: I think this library is well made. I spent a fair bit of my weekend looking at the code to figure out where things went wrong in my implementation, in hopes of improving this project and providing extra information for those who stumble upon it in the future, especially considering there isn't a whole lot of documentation apart from the readme file - at least as far as I can see.

The testing question was a genuine one; a question which I kind of answered myself two hours later after I set up additional runtimes on this dev machine and jumped into the testing suite. If the question was malicious I wouldn't have bothered looking further, but I did. I was actually close to filing a pull request to 'fix' the related functions and tests based on my initial assumptions, but while writing the pull request I realized that it was likely working the way you confirmed above.

Like yourself, my job also prevents me from being an open source maintainer. I only work on private repositories, so my public profile is intentionally empty.

**Comment by ConnerPhillis** [comment]
Hey @RaymondBakker,

I just wanted to apologize for the earlier message. I have no right to have interpreted your messages as I did, and I acted incredibly oversensitive without warrant. You came here asking for help and I took it as an insult, and that's not behavior that I consider excusable from myself.

I really appreciate the kind words, as much as I don't deserve them, and I'm sorry for any insult I caused. I feel like its hard to write a meaningful apology over the internet, so please take my words as sincere and my regret for how I acted as real.

When I get some free time I'll do what I can to make improvements to this library based on your suggestions, I'm fairly sure I have a 2.0 version on my school laptop that I never published that could shore up the most of it.

Thank you for using this, it was never really intended for public consumption (school project and all) but it's nice to hear that someone is hopefully getting some utility out of my work. Maybe I'll see what I can do about getting it ship-shape for a real release after this.
